server.port=8089


# Ethereum node URL (default to local node)
#ethereum.node.url=https://arb1.arbitrum.io/rpc
ethereum.node.url=https://arb-mainnet.g.alchemy.com/v2/zAztGaJpmhEJZo1f1wIns665r07-RGgB

# Uniswap V3 ETH/USDT 0.05% pool address
uniswap.v3.pool.address=0x11b815efB8f581194ae79006d24E0d814B7697F6





